[package]
name = "Rust_Crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
serde = { version = "1.0.215", features = ["derive"] }
log = "0.4.22"
rand = "0.9.0-beta.1"
postgres = "0.19.9"
colored = "3.0.0"