#[path = "Gamehelper/GameObjects/encounter.rs"]
pub(crate) mod encounter;

#[path = "Gamehelper/GameObjects/Items/consumable_item.rs"]
pub(crate) mod consumable_item;
#[path = "Gamehelper/GameObjects/Dungeon.rs"]
pub(crate) mod dungeon;
#[path = "Gamehelper/GameObjects/DungeonEncoutner/empty.rs"]
pub(crate) mod empty;
#[path = "Gamehelper/GameObjects/Items/equip_item.rs"]
pub(crate) mod equip_item;
#[path = "Gamehelper/GameObjects/Items/InventorySlot.rs"]
pub(crate) mod inventoryslot;
#[path = "Gamehelper/GameObjects/Item_Handler.rs"]
pub(crate) mod item_handler;
#[path = "Gamehelper/GameObjects/DungeonEncoutner/monster.rs"]
pub(crate) mod monster;
#[path = "Gamehelper/GameObjects/Items/passiv_handler.rs"]
pub(crate) mod passiv_handler;
#[path = "Gamehelper/GameObjects/player.rs"]
pub(crate) mod player;
#[path = "Gamehelper/GameObjects/DungeonEncoutner/trap.rs"]
pub(crate) mod trap;
#[path = "Gamehelper/GameObjects/DungeonEncoutner/treasure.rs"]
pub(crate) mod treasure;
#[path = "Gamehelper/GameObjects/Items/treasure_item.rs"]
pub(crate) mod treasure_item;
#[path = "Gamehelper/GameObjects/Items/weaponitem.rs"]
pub(crate) mod weaponitem;
